<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\OperationResultPattern\OperationResultPattern.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Common\" />
      <Folder Include="ValueObjects\Order\" />
      <Folder Include="ValueObjects\TimeSheet\" />
      <Folder Include="ValueObjects\UserValues\" />
    </ItemGroup>

</Project>
